language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/Bureau/MGL/Unit\ testing/gradle/

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build test
